version: "3"
services:      
  backend:
    container_name: yolonet_backend
    restart: unless-stopped
    build: ./backend
    links: 
      - mongo
    networks: 
      - yolonet

  mongo:
    container_name: yolonet_mongo
    image: mongo:latest
    ports: 
      - "27017:27017"
      - "27018:27017"
    networks: 
      - yolonet

  front:
    container_name: yolonet_front
    restart: unless-stopped
    build: ./client
    ports: 
      - "3000:3000"
    depends_on: 
      - backend
      - mongo
    networks: 
      - yolonet

networks:
  yolonet:
    driver: bridge