version: "3"
services:
  front:
    container_name: front_end
    build: ./client
    volumes:
      - ./client:/usr/src/app
    ports: 
      - "3000:3000"
    depends_on: 
      - backend
      - mongo
      
  backend:
    container_name: backend
    build: ./backend
    volumes: 
      - ./backend:/usr/src/app
    ports: 
      - "5000:5000"
    links: 
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    ports: 
      - "27017:27017"
      - "27018:27017"